openapi: 3.1.0
x-stoplight:
  id: h3n8zpb8rs93d
info:
  title: ApiTokens_Account
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{tokenId}':
    parameters:
      - schema:
          type: string
        name: tokenId
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: 6trfqjgni6lus
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: pz7ctdh6g3g7q
    post:
      summary: ''
      operationId: post-tokens-tokenId
      responses:
        '200':
          description: OK
      x-stoplight:
        id: hqgoo43alyp63
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token_id:
                  type: integer
                  x-stoplight:
                    id: z18huzt88ufax
                  format: int32
                  readOnly: true
                token:
                  type: integer
                  x-stoplight:
                    id: 8m2oolvyhf2zf
                  format: int32
                  readOnly: true
                user_id:
                  type: integer
                  x-stoplight:
                    id: h93cisofuxyaf
                  format: int32
                  readOnly: true
                expiration:
                  type: string
                  x-stoplight:
                    id: jg4q1c1xql8fd
                  format: date-time
                  readOnly: true
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: vay156bou5jmn
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: aqzfxbj4qcw5q
        firstName:
          type: string
          x-stoplight:
            id: 05gci2j5we9nb
        lastName:
          type: string
          x-stoplight:
            id: d0mcjzi7msnuv
        email:
          type: string
          format: email
          x-stoplight:
            id: a9mm21eyjtgf9
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: peyczey46fqv1
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: 7uvacdaczmhl9
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 2xgi0wqa2s13c
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: u8cbvqv90fkua
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
security:
  - API Key - 1: []
