openapi: 3.1.0
x-stoplight:
  id: 94h7bfmvkv6nu
info:
  title: API-ProyectoOFModificacion
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: vyjryi3gpdtoi
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: aetgye3p3231s
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: 42xhkxa2tm9ue
  /proyectoofmodificacion:
    get:
      summary: ProyectoOFModificacionFindMany
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        FechaHora:
                          type: string
                        Modificacion:
                          type: string
                        NombreUsuario:
                          type: string
                        ProcesoID:
                          type: integer
                        Proyecto_OFID:
                          type: integer
                        Proyecto_OFModificacionID:
                          type: integer
                        tipoComentario:
                          type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      - FechaHora: '2018-12-21T11:16:00.000'
                        Modificacion: "{\\rtf1\\ansi\\ansicpg1252\\deff0\\nouicompat\\deflang3082{\\fonttbl{\\f0\\fswiss\\fprq2\\fcharset0 Tahoma;}}\r\n{\\*\\generator Riched20 10.0.16299}\\viewkind4\\uc1 \r\n\\pard\\f0\\fs17 Pruebas\\par\r\n}\r\n"
                        NombreUsuario: DEMOS
                        ProcesoID: 0
                        Proyecto_OFID: 729
                        Proyecto_OFModificacionID: 1
                        tipoComentario: Notas
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: get-proyectoofmodificacion
      x-stoplight:
        id: g0qpev38dwy9q
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token Login
          required: true
        - schema:
            type: string
          in: query
          name: ProyectoOFID
        - schema:
            type: string
          in: query
          name: FechaStart
        - schema:
            type: string
          in: query
          name: FechaEnd
        - schema:
            type: string
          in: query
          name: TipoComentarioID
        - schema:
            type: string
          in: query
          name: ProcesoID
    post:
      summary: ProyectoOFModificacionCreate
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      proyecto_ofmodificacionID:
                        type: integer
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      proyecto_ofmodificacionID: 14
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: post-proyectoofmodificacion
      x-stoplight:
        id: rsl8r4jwpy4bp
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                FechaHora:
                  type: string
                Modificacion:
                  type: string
                NombreUsuario:
                  type: string
                ProcesoID:
                  type: integer
                Proyecto_OFID:
                  type: integer
                tipoComentario:
                  type: string
              x-examples:
                Example 1:
                  FechaHora: '20181221111600000'
                  Modificacion: teste
                  NombreUsuario: DEMOS
                  ProcesoID: 0
                  Proyecto_OFID: 729
                  tipoComentario: Notas
  '/proyectoofmodificacion/{proyecto_ofmodificacionID}':
    parameters:
      - schema:
          type: string
        name: proyecto_ofmodificacionID
        in: path
        required: true
      - schema:
          type: string
        name: proyecto_ofmodificacionID
        in: path
        required: true
      - schema:
          type: string
        name: proyecto_ofmodificacionID
        in: path
        required: true
    put:
      summary: ProyectoOFModificacionUpdate
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties:
                      proyecto_ofmodificacionID:
                        type: integer
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content:
                      proyecto_ofmodificacionID: 14
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: put-proyectoofmodificacion-proyecto_ofmodificacionID
      x-stoplight:
        id: 7ob7n1jlzadoj
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                FechaHora:
                  type: string
                Modificacion:
                  type: string
                NombreUsuario:
                  type: string
                ProcesoID:
                  type: integer
                Proyecto_OFID:
                  type: integer
                tipoComentario:
                  type: string
              x-examples:
                Example 1:
                  FechaHora: '20181221111600000'
                  Modificacion: testev2
                  NombreUsuario: DEMOS
                  ProcesoID: 0
                  Proyecto_OFID: 729
                  tipoComentario: Notas
    delete:
      summary: ProyectoOFModificacionDelete
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                  content:
                    type: object
                    properties: {}
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
                    content: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  message:
                    type: string
                x-examples:
                  Example 1:
                    statusCode: 200
                    message: Request processed successfully
      operationId: delete-proyectoofmodificacion-proyecto_ofmodificacionID
      x-stoplight:
        id: bknimji37630q
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token Login
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: gacnby4jh3bmt
        firstName:
          type: string
          x-stoplight:
            id: wp9afhxtbcu3z
        lastName:
          type: string
          x-stoplight:
            id: f3k5shye5pwej
        email:
          type: string
          format: email
          x-stoplight:
            id: rbg4lf673kewz
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: z0ykow2pbuh47
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: nqnje7m2dxull
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: zeff5r7o66az4
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: v261ktlboqrpk
