openapi: 3.0.0
x-stoplight:
  id: zjjr8oq5slwyj
info:
  title: ApiInterventions
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/intervention/externalWork/{procesoID}':
    parameters:
      - schema:
          type: string
        name: procesoID
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  ProcesoTrabajoExteriorID:
                    type: string
                  ProcesoID:
                    type: string
                  Fecha:
                    type: string
                  Importe:
                    type: string
                  MailingID:
                    type: string
                  Notas:
                    type: string
                  UsuarioID:
                    type: string
                  NumeroFactura:
                    type: string
                  AlbaranCompraLineaID:
                    type: string
                  FechaFactura:
                    type: string
                x-examples:
                  Example 1:
                    ProcesoTrabajoExteriorID: ''
                    ProcesoID: ''
                    Fecha: ''
                    Importe: ''
                    MailingID: ''
                    Notas: ''
                    UsuarioID: ''
                    NumeroFactura: ''
                    AlbaranCompraLineaID: ''
                    FechaFactura: ''
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
        - schema:
            type: string
          in: query
          name: procesoID
          description: ID del Proceso
  /intervention/externalWork:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  ProcesoTrabajoExteriorID: ''
                  ProcesoID: ''
                  Fecha: ''
                  Importe: ''
                  MailingID: ''
                  Notas: ''
                  UsuarioID: ''
                  NumeroFactura: ''
                  AlbaranCompraLineaID: ''
                  FechaFactura: ''
              properties:
                ProcesoID:
                  type: string
                Fecha:
                  type: string
                Importe:
                  type: string
                MailingID:
                  type: string
                Notas:
                  type: string
                UsuarioID:
                  type: string
                NumeroFactura:
                  type: string
                AlbaranCompraLineaID:
                  type: string
                FechaFactura:
                  type: string
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
    parameters: []
  '/intervention/externalWork/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-intervention-externalWork-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ProcesoTrabajoExteriorID:
                    type: string
                  ProcesoID:
                    type: string
                  Fecha:
                    type: string
                  Importe:
                    type: string
                  MailingID:
                    type: string
                  Notas:
                    type: string
                  UsuarioID:
                    type: string
                  NumeroFactura:
                    type: string
                  AlbaranCompraLineaID:
                    type: string
                  FechaFactura:
                    type: string
                x-examples:
                  Example 1:
                    ProcesoTrabajoExteriorID: ''
                    ProcesoID: ''
                    Fecha: ''
                    Importe: ''
                    MailingID: ''
                    Notas: ''
                    UsuarioID: ''
                    NumeroFactura: ''
                    AlbaranCompraLineaID: ''
                    FechaFactura: ''
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
        - schema:
            type: string
          in: query
          name: id
          description: ID del Proceso Trabajo Exterior
    delete:
      summary: ''
      operationId: delete-intervention-externalWork-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ProcesoTrabajoExteriorID:
                    type: string
                x-examples:
                  Example 1:
                    ProcesoTrabajoExteriorID: ''
      parameters:
        - schema:
            type: string
          in: header
          name: accessToken
          description: Token de validación de sesión
        - schema:
            type: string
          in: query
          name: id
          description: ID del Proceso Trabajo Exterior
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
